idf_component_register(
    SRCS
        "wave_rover_hal.c"
        "wave_rover_motor.c"
        "wave_rover_power.c"
        "wave_rover_imu.c"
        "wave_rover_nav.c"
        "wave_rover_display.c"
    INCLUDE_DIRS "include"
    PRIV_INCLUDE_DIRS
        "${CMAKE_CURRENT_SOURCE_DIR}/../../boards/wave_rover"
    PRIV_REQUIRES
        esp_driver_i2c
        esp_driver_ledc
        esp_driver_gpio
        esp_timer
        log
        esp_common
        freertos
        nvs_flash
)
